In [3]:
import torch

device = 'cuda' if torch.cuda.is_available() else 'cpu'

my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32, device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0


#### Other initialization methods

In [21]:
x = torch.empty(size=(3, 3))
x = torch.zeros((3, 3))
print(x)

# Initializing numbers from a random normal distribution
x = torch.rand((3, 3))
print(x)
x = torch.ones((3, 3))
print(x)
# Identity matric I (eye)
x = torch.eye(5, 5)
print(x)
x = torch.arange(start=0, end=5, step=1)
print(x)
x = torch.linspace(start=0.1, end=1, steps=10)
print(x)
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)
print(x)
x = torch.empty(size=(1, 5)).uniform_(0, 1)
print(x)
x = torch.diag(torch.ones(3))
print(x)


tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[0.3959, 0.5340, 0.0657],
        [0.7346, 0.8676, 0.0947],
        [0.0415, 0.2755, 0.8815]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
tensor([0, 1, 2, 3, 4])
tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])
tensor([[-2.0310,  1.3917,  0.1401,  0.0098,  0.2008]])
tensor([[0.7608, 0.2810, 0.9994, 0.3113, 0.0268]])
tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])


#### How to initialize and convert tensors to other types (int, float, double)

In [26]:
tensor = torch.arange(4)
print(tensor)
print(tensor.bool())
print(tensor.short()) # int16
print(tensor.long()) # int64
print(tensor.half()) # float16
print(tensor.float()) # float32
print(tensor.double()) # float64

tensor([0, 1, 2, 3])
tensor([False,  True,  True,  True])
tensor([0, 1, 2, 3], dtype=torch.int16)
tensor([0, 1, 2, 3])
tensor([0., 1., 2., 3.], dtype=torch.float16)
tensor([0., 1., 2., 3.])
tensor([0., 1., 2., 3.], dtype=torch.float64)


#### Array to tensor conversion and vice-versa

In [29]:
import numpy as np

np_array = np.zeros((5, 5))
print(np_array)
tensor = torch.from_numpy(np_array)
print(tensor)
np_array_back = tensor.numpy()
print(np_array_back)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]], dtype=torch.float64)
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


#### Tensor math and comparison operations

In [56]:
x = torch.tensor([1, 2, 3])
y = torch.tensor([9, 8, 7])

# Addition
z1 = torch.empty(3)
torch.add(x, y, out=z1)
print(z1)

z2 = torch.add(x, y)
print(z2)

z = x + y
print(z)

# Substraction
z = x - y
print(z)

# Division
z = torch.true_divide(x, y) # Element wise division if their shape is same
print(z)

# Inplace Operations
# -- are the type of operations with which transforms the input using no auxiliary data structure. Inplace means that the algor-
# ...-ithm does not use extra space for maipulating the the input but may require a small though nonconstant extra space for 
# ...its operation
t = torch.zeros(3)
t.add_(x)
t += x
print(t)

# Exponentiation
z = x.pow(2)
z = x ** 2
print(z)

# Matrix Multiplication
x1 = torch.rand((2, 5))
x2 = torch.rand((5, 3))
x3 = torch.mm(x1, x2) # (2, 3)
print(x3)
x3 = x1.mm(x2)

# Matrix Exponentiation
matrix_exp = torch.rand(5, 5)
print(matrix_exp.matrix_power(3))

# Element wise multiplication
z = x * y
print(z)

# Batch matrix multiplication
batch = 32
n = 10
m = 20
p = 30

tensor1 = torch.rand((batch, n, m))
tensor2 = torch.rand((batch, m , p))
out_bmm = torch.bmm(tensor1, tensor2) 
print(out_bmm.shape)

# Example of broadcasting
x1 = torch.rand((5, 5))
x2 = torch.rand((1, 5))

z = x1 - x2
z = x1 ** x2

# Other useful tensor operations
sum_x = torch.sum(x, dim=0)
print(sum_x)

tensor([10., 10., 10.])
tensor([10, 10, 10])
tensor([10, 10, 10])
tensor([-8, -6, -4])
tensor([0.1111, 0.2500, 0.4286])
tensor([2., 4., 6.])
tensor([1, 4, 9])
tensor([[1.4833, 0.9691, 1.4161],
        [0.7254, 1.4530, 1.3615]])
tensor([[0.8956, 1.7779, 2.3908, 1.7695, 1.5930],
        [0.8339, 1.7003, 2.1482, 1.6684, 1.6554],
        [1.0916, 2.2373, 2.7294, 2.1801, 2.1654],
        [1.3757, 2.8409, 3.6035, 2.7710, 2.5148],
        [0.9484, 2.0083, 2.6535, 1.9711, 1.7435]])
tensor([ 9, 16, 21])
torch.Size([32, 10, 30])
tensor(6)


In [ ]:
# Other useful tensor operations
sum_x = torch.sum(x, dim=0)
values, indices = torch.max(x, dim=0)
values, indices = torch.min(x, dim=0)
abs_x = torch.abs(x)
z = torch.argmax(x, dim=0) # Returns only the index
z = torch.argmin(x, dim=0)
# Torch cal mean of only the float dataset
mean_x = torch.mean((x.float(), dim=0))
z = torch.eq(x, y)
sorted_y, indices = torch.sort(y, dim=0, descending=False)

z = torch.clamp(x, min=0)


In [61]:
# Fancy Indexing

x = torch.rand([3, 5])
rows = torch.tensor([1, 0])
cols = torch.tensor([4, 0])
print(x[rows, cols])
print(x)

tensor([0.2324, 0.5376])
tensor([[0.5376, 0.6298, 0.2601, 0.8268, 0.2718],
        [0.2230, 0.0699, 0.0602, 0.9817, 0.2324],
        [0.2270, 0.8992, 0.3721, 0.6662, 0.9526]])


In [64]:
# More advanced indexing
x = torch.arange(10)
print(x[(x < 2) ^ (x > 8)])
print(x[x.remainder(2) == 0])

tensor([0, 1, 9])
tensor([0, 2, 4, 6, 8])


In [68]:
# Useful operations
print(x)
print(torch.where(x > 5, x, x*2))
print(torch.tensor([0,0,1,2,2,3,4]).unique())
print(x.ndimension())
print(x.numel())

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
tensor([ 0,  2,  4,  6,  8, 10,  6,  7,  8,  9])
tensor([0, 1, 2, 3, 4])
1
10


#### Tensor Reshaping

In [70]:
x = torch.arange(9)
print(x)

# Main difference between reshape and view is that view is used when the elements of the tensor are in contigous memory
x_3x3 = x.view(3, 3)
print(x_3x3)

# Another method for this is our traditional method called reshape
x_3x3 = x.reshape(3, 3)
print(x_3x3)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])
tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])


In [74]:
# So, we try to reform a matrix that has been transposed and no longer holds the contigous memory then we need to make the 
# ... current matrix contigous 
y = x_3x3.t()
print(x)
print(y)
print(y.contiguous().view(9))

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8])
tensor([[0, 3, 6],
        [1, 4, 7],
        [2, 5, 8]])
tensor([0, 3, 6, 1, 4, 7, 2, 5, 8])


In [77]:
x1 = torch.rand((2, 5))
x2 = torch.rand((2, 5))

print(torch.cat((x1, x2), dim=0).shape)

# Convert the tensor back to one dimension for that we need to use view(-1)
print(x1.view(-1))

torch.Size([4, 5])
tensor([0.9883, 0.6000, 0.7500, 0.7172, 0.1219, 0.3432, 0.0158, 0.8073, 0.4567,
        0.7166])


In [83]:
batch = 64
x = torch.rand((batch, 2, 5))
z = x.view(batch, -1)
print(z.shape)

print(x.shape)
z = x.permute(0, 2, 1)
print(z.shape)


torch.Size([64, 10])
torch.Size([64, 2, 5])
torch.Size([64, 5, 2])


In [91]:
# Squeezing and unsqueezing
x = torch.arange(10)
print(x.unsqueeze(0))
print(x.unsqueeze(1))
x = torch.arange(10).unsqueeze(0).unsqueeze(1)
x.squeeze(0).shape

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])
tensor([[0],
        [1],
        [2],
        [3],
        [4],
        [5],
        [6],
        [7],
        [8],
        [9]])


torch.Size([1, 10])

In [2]:
import torch
x = torch.arange(10)
x

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
x.unsqueeze(0).squeeze(1)

tensor([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])