In [1]:
import torch

In [2]:
example_tensor = torch.Tensor(
    [
     [[1, 2], [3, 4]], 
     [[5, 6], [7, 8]], 
     [[9, 0], [1, 2]]
    ]
)

In [4]:
example_tensor.shape

torch.Size([3, 2, 2])

In [5]:
example_tensor.device

device(type='cpu')

In [6]:
#You can also get the size of a particular dimension $n$ using example_tensor.shape[n] or equivalently example_tensor.size(n)
print("shape[0] =", example_tensor.shape[0])
print("size(1) =", example_tensor.size(1))

shape[0] = 3
size(1) = 2


In [7]:
print("Rank =", len(example_tensor.shape))
print("Number of elements =", example_tensor.numel())

Rank = 3
Number of elements = 12


In [8]:
example_tensor[1, 1, 0].item()

7.0

In [9]:
torch.ones_like(example_tensor)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])

In [10]:
torch.zeros_like(example_tensor)

tensor([[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]])

In [11]:
torch.randn_like(example_tensor)


tensor([[[ 1.6863, -0.0329],
         [-1.6199,  1.0412]],

        [[ 0.2155, -0.1482],
         [-2.3975, -2.2193]],

        [[-0.7159,  0.4045],
         [ 0.1365,  0.6040]]])

In [12]:
torch.randn(2, 2, device='cuda') # Alternatively, for a GPU tensor, you'd use device='cuda'

tensor([[-0.5498,  0.0866],
        [ 1.1538, -0.9847]], device='cuda:0')